// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBL3xulk6xaMVcczh3tyS33DY1grbGCOIg',
    appId: '1:945670712135:web:1c00d19a08cbb9b98a7a62',
    messagingSenderId: '945670712135',
    projectId: 'learning-20829',
    authDomain: 'learning-20829.firebaseapp.com',
    storageBucket: 'learning-20829.firebasestorage.app',
    measurementId: 'G-63FVRHYGZV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCptBSNViHdBcofdOTsLICkrQrhtHJldVU',
    appId: '1:945670712135:android:1454b9e5cfa204848a7a62',
    messagingSenderId: '945670712135',
    projectId: 'learning-20829',
    storageBucket: 'learning-20829.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWz-XB_cDCEQ2s-iYMdiIo2m0jftYdY50',
    appId: '1:945670712135:ios:e6a698408bd690568a7a62',
    messagingSenderId: '945670712135',
    projectId: 'learning-20829',
    storageBucket: 'learning-20829.firebasestorage.app',
    iosBundleId: 'com.dicoding.ditonton',
  );
}
